version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: app
    restart: always
    build: .
    env_file: .env.local
    environment:
      - PORT=${PORT}
      - MONGO_URL=${MONGO_URL}
    ports:
      - 4000:80
    external_links:
      - mongo
    depends_on:
      - mongo
    links:
      - mongo